### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hseeberger** [agourlay/cornichon#1]
@agourlay, thank's for putting this together! You have asked for feedback, so here we go:

- First, I don't fully understand what additional features chrnichon offers over using ScalaTest (e.g. using a `FeatureSpec`) in combination with the akka-http-testkit
- Second, using snake_case is not idiomatic Scala, you better switch to camelCase

**Comment by agourlay** [comment]
@hseeberger Thanks  a lot for the feedback! 

- Cornichon vs plain Scalatest

Cornichon targets the same sweet spot as Cucumber does, i.e offering a common language between developers and less technical people to share specifications and describe behaviours. But in more typesafe way of course :)

I would argue that the current DSL from Cornichon is easier to read and a clearer way to share HTTP specification than a plain Scalatest class.

Also Cornichon is a higher abstraction offering the concept of "scenario session" built-in. Meaning, you can extract and save part of the response for later reuse via assertion block and/or placeholders.

For concrete example see https://github.com/agourlay/cornichon/blob/master/src/test/scala/com/github/agourlay/cornichon/examples/CornichonExamplesSpec.scala#L192

This is in my (biased) opinion a cleaner way to propagate change and state than playing with vars inside a FeatureSpec.

- Snake-case

All the functions using snake_case are living in the DSL because I thought it will be easier to read for non Scala people. But I am not really opiniated about that :)

**Comment by hseeberger** [comment]
Thanks for the quick response. 

I'm not sure I like the scenario session, because I prefer simple and strongly typed bindings (vals) over using maps and naming conventions (<superhero>). But hey, I'm a technical person and hence probably not within your target audience anyway, so take my feedback with a grain of salt.

One other comment: Always calling `toJson` is cumbersome. Either overload the methods to accept `String`s and convert internally or provide an implicit conversion.

**Comment by agourlay** [comment]
I really want developers to enjoy writing Cornichon tests so I will keep your feedback in mind!
