### ISSUE TITLE
WithHeader ends in "terminated abruptly"

### ISSUE THREAD

**Issue by hajoeichler** [agourlay/cornichon#167]
This is my test:
```
import com.github.agourlay.cornichon.CornichonFeature

class WithHeaderSpec extends CornichonFeature {
  def feature = Feature("WithHeader should work"){
    Scenario("Define some header around the steps."){
      WithHeaders(("Some", "Value")) {
        When I post("http://localhost:8888/products").withBody(
          """
          {
            "foo":"bar"
          }
          """
        )
        Then assert status.is(200)
      }
    }
  }
}
```

When I execute it, it starts, but end before the first step can be executed.
```
[info] WithHeaderSpec:
[info] WithHeader should work
[info] - should Define some header around the steps.
[ERROR] [12/23/2017 22:43:50.829] [cornichon-actor-system-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(cornichon-actor-system)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://cornichon-actor-system/user/StreamSupervisor-1/flow-7-0-mergePreferred#-268362809]] terminated abruptly)
```
I played a bit more. If the `WithHeader` wrapper is used later in a scenario the steps before are executed, but as soon as it enters the wrapper the execution is terminated.

**Comment by agourlay** [comment]
This is extremely strange, it looks like an issue with the underlying `akka-http` client.
To gather more info, you can try the following.

Create an application.conf file in your `src/test/resources` folder and write the following.

```
cornichon {
  traceRequests = true
  warnOnDuplicateHeaders = true
}
```

It will output a verbose output with the requests sent so that you can control that those are properly formed.

Then you could try to add `useExperimentalHttp4sClient = true` in the same cornichon configuration block to used another built-in http client. 

I already had strange issues with `akka-http` so I would not be surprised if the above configuration works.

If it still fails, I will have to digg a bit more 😈

**Comment by hajoeichler** [comment]
`useExperimentalHttp4sClient = true` did the trick so far.

**Comment by agourlay** [comment]
Great news.
The goal is to promote the `http4s` client as the default client in the future.
It is currently not possible because it misses a couple of feature to be on par with `akka-http`.

I will close the issue for the time being.
