### ISSUE TITLE
HttpDsl always expects Json and doesn't allow for eg. text/plain body.

### ISSUE THREAD

**Issue by anandsahil** [agourlay/cornichon#419]
Hi, I am struggling to find a way to save text/plan body in the session, it always error's out as it always expects a JSON.

**Comment by agourlay** [comment]
Thank you for the bug report 👍 

This is indeed a real bug cause by the `HttpDSL` wrongly expecting a JSON payload.
I have found the bug and the fix is rather straight forward.

As mentioned on [Gitter](https://gitter.im/agourlay/cornichon?at=5f7d757f6e0eb844696e3901), either I push my fix or you can give it a try as a learning exercise 😄

**Comment by agourlay** [comment]
I went ahead a proposed my fix https://github.com/agourlay/cornichon/pull/420

**Comment by anandsahil** [comment]
Thanks for the fix @agourlay :-)
